# Generated by Django 3.2.5 on 2021-07-24 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.IntegerField()),
                ('lat_start', models.FloatField()),
                ('lat_end', models.FloatField()),
                ('lon_start', models.FloatField()),
                ('lon_end', models.FloatField()),
            ],
        ),
    ]
