# Generated by Django 3.2.5 on 2021-07-24 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidos',
            name='id',
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='hora',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
