# Generated by Django 3.2.5 on 2021-07-24 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0002_auto_20210724_0441'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fechas',
            fields=[
                ('fecha', models.DateField(primary_key=True, serialize=False)),
                ('pedidos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datos.pedidos')),
            ],
        ),
    ]
