# Generated by Django 3.2.5 on 2021-07-24 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0003_fechas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidos',
            name='hora',
        ),
        migrations.AddField(
            model_name='pedidos',
            name='time',
            field=models.DateTimeField(auto_now=True, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Fechas',
        ),
    ]
