# Generated by Django 3.2.5 on 2021-07-24 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0004_auto_20210724_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='time',
            field=models.DateTimeField(primary_key=True, serialize=False),
        ),
    ]
