# Generated by Django 3.2.5 on 2021-07-24 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0007_alter_pedidos_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('last_update', models.CharField(max_length=10)),
                ('lat', models.FloatField()),
                ('long', models.FloatField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=13)),
                ('lat_start', models.FloatField()),
                ('lat_end', models.FloatField()),
                ('long_start', models.FloatField()),
                ('long_end', models.FloatField()),
            ],
            options={
                'ordering': ['time'],
            },
        ),
        migrations.DeleteModel(
            name='Pedidos',
        ),
        migrations.AddField(
            model_name='conductor',
            name='pedidos',
            field=models.ManyToManyField(to='datos.Pedido'),
        ),
    ]
