# Generated by Django 3.2.5 on 2021-07-24 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0008_auto_20210724_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conductor',
            name='pedidos',
            field=models.ManyToManyField(blank=True, to='datos.Pedido'),
        ),
    ]
