# Generated by Django 3.2.5 on 2021-07-25 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0009_alter_conductor_pedidos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedido',
            options={'ordering': ['fecha', 'hora']},
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='time',
        ),
        migrations.AddField(
            model_name='pedido',
            name='fecha',
            field=models.CharField(default='0000/00/00', max_length=10),
        ),
        migrations.AddField(
            model_name='pedido',
            name='hora',
            field=models.IntegerField(default=0),
        ),
    ]
